### ISSUE TITLE
Perform node before before creating python sdist

### ISSUE THREAD

**Issue by jonringer** [vidartf/ipydatawidgets#44]
It's quite painful for distro's to perform sandboxed builds involving two toolchains, please export the built js artifacts before creating the python sdist.

**Comment by vidartf** [comment]
I'm not sure what is being asked here. What do you mean when you say "please export the built js artifacts" ?

**Comment by jonringer** [comment]
Builds occur in an offline sandbox, so I can't do logic like: https://github.com/vidartf/ipydatawidgets/blob/da6db7a9f9ace74c87583e633b22c3634526520e/setup.py#L55

It would be nice for the javascript to have already occured, and those build artifacts be included in the sdist.

**Comment by vidartf** [comment]
I'm still confused. All of the data files are distributed with the sdist. If you are seeing something else, please be more specific.

**Comment by vidartf** [comment]
Guessing a little bit here, but: Have you tried adding the `--skip-npm` flag? I.e. `python setup.py bdist_wheel --skip-npm` ?

**Comment by jonringer** [comment]
> Guessing a little bit here, but: Have you tried adding the `--skip-npm` flag? I.e. `python setup.py bdist_wheel --skip-npm` ?

I have not

**Comment by jonringer** [comment]
```
running js
`npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
Traceback (most recent call last):
  File "/build/ipydatawidgets-4.2.0/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 137, in <module>
    setup(**setup_args)
  File "/nix/store/0kk44adw7gbvgskds4ic56fr5zahbh8j-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nix/store/d8176dzb7lvk7cpqpsnakcxka8n3jy75-python3.9-jupyter-packaging-0.10.2/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 632, in run
    [self.run_command(cmd) for cmd in cmds]
  File "/nix/store/d8176dzb7lvk7cpqpsnakcxka8n3jy75-python3.9-jupyter-packaging-0.10.2/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 632, in <listcomp>
    [self.run_command(cmd) for cmd in cmds]
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nix/store/d8176dzb7lvk7cpqpsnakcxka8n3jy75-python3.9-jupyter-packaging-0.10.2/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 315, in run
    c.run()
  File "/nix/store/d8176dzb7lvk7cpqpsnakcxka8n3jy75-python3.9-jupyter-packaging-0.10.2/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 403, in run
    raise ValueError(('missing files: %s' % missing))
ValueError: missing files: ['/build/ipydatawidgets-4.2.0/packages/jlabextension/build/index.js']
```

> Guessing a little bit here, but: Have you tried adding the --skip-npm flag? I.e. python setup.py bdist_wheel --skip-npm ?

That was the fix! sorry for bothering you

**Comment by jonringer** [comment]
Thanks @vidartf, guess this was more of an issue with my unfamiliar with `jupyter_packaging`
